/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./components/ComponentList.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    IconBeta: typeof import('./components/IconBeta.vue')['default']
    LarkLogo: typeof import('./components/LarkLogo.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TestText: typeof import('./components/TestText.vue')['default']
  }
}
